name: Deploy

on:
  # Run this workflow whenever a new commit is pushed to main.
  push: {branches: [main]}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install -g npm@latest
      - run: npm config set registry https://registry.npmjs.org
      - run: npm ci
      - name: Upload npm debug log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: npm-debug-log
          path: /home/runner/.npm/_logs/
      - run: npm run build
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4